# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Tomecs Day Boke
url: http://tomecs.github.com
feed: /atom.xml
author_info: <a href="http://tomecs.github.com/">tomecs</a>

myblog:
  gavatar: images/2.jpg
  gpname: tomecs
  linkedin: http://www.linkedin.com/in/taotaoli
  github: https://github.com/tomecs
  email: mailto:taotao.engineer@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
